# Generated by Django 3.0.4 on 2020-03-08 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('total_right_answers', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.QuizModule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestDetailedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_answer_correct', models.BooleanField(default=False)),
                ('attempted_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Questions')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.Options')),
                ('test_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.TestInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
